export const DAYONE_PROJECT = {
  key: "dayone-web",
  name: "dayone-web",
  repository: "ianjuantw/dayone",
  branch: "main",
} as const;

export const DEFAULT_STEPS = [
  {
    slug: "get-access",
    title: "Get access",
    description: "Confirm the accounts, repository, and people you need.",
  },
  {
    slug: "run-locally",
    title: "Run locally",
    description: "Bring the repository up on your own machine.",
  },
  {
    slug: "know-the-system",
    title: "Know the system",
    description: "Trace a real request through the services you will touch.",
  },
  {
    slug: "make-a-change",
    title: "Make a change",
    description: "Ship a small, safe improvement with confidence.",
  },
  {
    slug: "ship-first-mr",
    title: "Ship first MR",
    description: "Submit the first pull request link and close the feedback loop.",
  },
] as const;

export const DEFAULT_TASKS = [
  {
    step: "get-access",
    slug: "repository-access",
    label: "Repository access",
    detail: "Confirm you can open and clone ianjuantw/dayone",
    status: "ready",
  },
  {
    step: "get-access",
    slug: "team-channel",
    label: "Support path identified",
    detail: "Confirm where repository questions and blockers should be raised",
    status: "ready",
  },
  {
    step: "get-access",
    slug: "credentials",
    label: "GitHub authentication",
    detail: "Confirm Git can authenticate with the intended GitHub account",
    status: "ready",
  },
  {
    step: "get-access",
    slug: "buddy-intro",
    label: "Reviewer identified",
    detail: "Confirm who will review the first pull request",
    status: "ready",
  },
  {
    step: "run-locally",
    slug: "runtime",
    label: "Runtime is ready",
    detail: "Doctor will compare Node.js with the project requirement",
    status: "ready",
  },
  {
    step: "run-locally",
    slug: "dependencies",
    label: "Dependencies installed",
    detail: "Doctor will verify installed project packages",
    command: "npm install",
    status: "ready",
  },
  {
    step: "run-locally",
    slug: "git",
    label: "Git checkout",
    detail: "Doctor will verify the repository and current branch",
    status: "ready",
  },
  {
    step: "run-locally",
    slug: "secrets",
    label: "Environment configuration",
    detail: "Doctor will determine whether any environment values are required",
    status: "ready",
  },
  {
    step: "run-locally",
    slug: "database",
    label: "Local database",
    detail: "Doctor will determine whether local database tooling is required",
    status: "ready",
  },
  {
    step: "run-locally",
    slug: "local-health",
    label: "DayOne local health",
    detail: "Start this app and verify its signed loopback health response",
    command: "node cli/dayone.mjs --health-url http://localhost:3000/api/health --json",
    status: "ready",
  },
  {
    step: "know-the-system",
    slug: "request-flow",
    label: "Trace a request",
    detail: "Follow bootstrap from the browser through the route handler and D1",
    status: "ready",
  },
  {
    step: "know-the-system",
    slug: "ownership-map",
    label: "Know service ownership",
    detail: "Learn who owns each service and escalation path",
    status: "ready",
  },
  {
    step: "know-the-system",
    slug: "routing-quiz",
    label: "Check your mental model",
    detail: "Choose where onboarding state transitions are enforced",
    status: "ready",
  },
  {
    step: "make-a-change",
    slug: "development-branch",
    label: "Create a development branch",
    detail: "Start from the latest main branch",
    command: "git switch -c docs/onboarding-improvement",
    status: "ready",
  },
  {
    step: "make-a-change",
    slug: "first-change",
    label: "Make the first safe change",
    detail: "Clarify one real instruction in docs/environment-doctor.md",
    status: "ready",
  },
  {
    step: "make-a-change",
    slug: "tests",
    label: "Run project checks",
    detail: "Run the doctor tests and lint before pushing",
    command: "node --test tests/dayone-cli.test.mjs && npm run lint",
    status: "ready",
  },
  {
    step: "ship-first-mr",
    slug: "push-branch",
    label: "Push your branch",
    detail: "Publish the branch to the shared repository",
    command: "git push -u origin HEAD",
    status: "ready",
  },
  {
    step: "ship-first-mr",
    slug: "open-merge-request",
    label: "Open the merge request",
    detail: "Use the team template and describe how you verified the change",
    status: "ready",
  },
  {
    step: "ship-first-mr",
    slug: "request-review",
    label: "Request review",
    detail: "Ask your buddy and the service owner for review",
    status: "ready",
  },
  {
    step: "ship-first-mr",
    slug: "share-feedback",
    label: "Share onboarding feedback",
    detail: "Turn reproducible friction into a platform backlog item",
    status: "ready",
  },
] as const;

export const DEFAULT_SERVICES = [
  {
    id: "dayone-web:ui",
    name: "DayOne UI",
    kind: "client",
    description: "app/page.tsx requests the canonical journey and renders user actions.",
  },
  {
    id: "dayone-web:route",
    name: "API route",
    kind: "route",
    description: "app/api/* validates HTTP input and delegates to the domain layer.",
  },
  {
    id: "dayone-web:auth",
    name: "ChatGPT identity",
    kind: "auth",
    description: "app/chatgpt-auth.ts reads server-provided authenticated-user headers.",
  },
  {
    id: "dayone-web:domain",
    name: "Journey service",
    kind: "service",
    description: "db/dayone.ts owns task guards, reconciliation, blockers, and metrics.",
  },
  {
    id: "dayone-web:d1",
    name: "Cloudflare D1",
    kind: "database",
    description: "Drizzle persists profiles, journeys, doctor evidence, blockers, and sources.",
  },
] as const;

export const DEFAULT_GUIDE_SOURCES = [
  {
    id: "dayone-web:setup",
    topic: "environment",
    title: "Local setup guide",
    type: "repository",
    locator: "README.md#run-locally",
    excerpt: "Install dependencies, start the app, then verify the build and lint checks.",
    priority: 10,
  },
  {
    id: "dayone-web:doctor",
    topic: "environment",
    title: "Environment doctor reference",
    type: "repository",
    locator: "docs/environment-doctor.md",
    excerpt: "Warnings remain visible but non-blocking; explicit failures require a fresh report.",
    priority: 20,
  },
  {
    id: "dayone-web:architecture",
    topic: "architecture",
    title: "Request flow map",
    type: "architecture",
    locator: "docs/architecture/request-flow.md",
    excerpt: "The UI calls a vinext route, authenticated headers identify the user, domain rules reconcile state, and Drizzle writes D1.",
    priority: 10,
  },
  {
    id: "dayone-web:ownership",
    topic: "people",
    title: "Repository ownership guide",
    type: "person",
    locator: "docs/onboarding/ownership.md",
    excerpt: "DayOne records escalation context but does not notify a person; share it with the chosen reviewer or repository maintainer.",
    priority: 10,
  },
  {
    id: "dayone-web:delivery",
    topic: "delivery",
    title: "First merge request checklist",
    type: "repository",
    locator: ".github/pull_request_template.md",
    excerpt: "Keep the first change small, include verification evidence, and request review from your buddy.",
    priority: 10,
  },
  {
    id: "dayone-web:access",
    topic: "access",
    title: "Developer access checklist",
    type: "runbook",
    locator: "docs/onboarding/access.md",
    excerpt: "Repository, team channel, credential manager, and buddy access should be confirmed before setup.",
    priority: 10,
  },
] as const;
